/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE / Your Name
 * @brief          : Dual External Interrupt (EXTI) Handler Example
 * @description    : PA10 turns on the LED (PA5), PB12 turns it off.
 * Both trigger on a falling edge and share the same IRQ.
 ******************************************************************************
 */

#include <stdint.h>

/* --- 1. Register Memory Mapping --- */

// Clock Control Registers
#define RCC_AHB1ENR (*(volatile uint32_t *)0x40023830) // AHB1 Peripheral Clock Enable (GPIO)
#define RCC_APB2ENR (*(volatile uint32_t *)0x40023844) // APB2 Peripheral Clock Enable (SYSCFG)

// GPIO Registers
#define GPIOA_MODER (*(volatile uint32_t *)0x40020000) // Mode register for Port A (Fixed Address)
#define GPIOA_ODR   (*(volatile uint32_t *)0x40020014) // Output data register for Port A
#define GPIOB_MODER (*(volatile uint32_t *)0x40020400) // Mode register for Port B
#define GPIOA_PUPDR (*(volatile uint32_t *)0x4002000C) //PUPDR for port A
#define GPIOB_PUPDR (*(volatile uint32_t *)0x4002040C) //PUPDR for port B

// System Configuration Registers (Multiplexers for EXTI lines)
#define SYSCFG_EXTICR3 (*(volatile uint32_t *)0x40013810) // Manages EXTI lines 8 to 11
#define SYSCFG_EXTICR4 (*(volatile uint32_t *)0x40013814) // Manages EXTI lines 12 to 15

// EXTI (External Interrupt) Registers
#define EXTI_IMR  (*(volatile uint32_t *)0x40013C00) // Interrupt Mask Register (Enables lines)
#define EXTI_FTSR (*(volatile uint32_t *)0x40013C0C) // Falling Trigger Selection Register
#define EXTI_PR   (*(volatile uint32_t *)0x40013C14) // Pending Register (Interrupt status flags)

// NVIC (Nested Vectored Interrupt Controller) Register
#define NVIC_ISER1 (*(volatile uint32_t *)0xE000E104) // Interrupt Set-Enable Register 1 (IRQs 32-63)


/* --- 2. Interrupt Service Routine (ISR) --- */

/**
 * @brief This handler catches all EXTI lines from 10 to 15.
 * Since we are using line 10 and 12, we must check the Pending Register
 * to find out which pin triggered the interrupt.
 */
void EXTI15_10_IRQHandler(void){

    // Check if EXTI Line 10 (PA10) triggered the interrupt
    if(EXTI_PR & (1 << 10)){
        // Clear the pending flag for line 10 (Write 1 to clear)
        EXTI_PR |= (1 << 10);
        // Action: Turn ON the LED on PA5
        GPIOA_ODR |= (1 << 5);
    }

    // Check if EXTI Line 12 (PB12) triggered the interrupt
    if(EXTI_PR & (1 << 12)){
        // Clear the pending flag for line 12 (Write 1 to clear)
        EXTI_PR |= (1 << 12);
        // Action: Turn OFF the LED on PA5
        GPIOA_ODR &= ~(1 << 5);
    }
}


/* --- 3. Main Program --- */

int main(void)
{
    /* A. ENABLE PERIPHERAL CLOCKS */
    // Enable clocks for GPIOA (Bit 0) and GPIOB (Bit 1)
    RCC_AHB1ENR |= (3 << 0);
    // Enable clock for SYSCFG (Bit 14) to route interrupts
    RCC_APB2ENR |= (1 << 14);

    /* B. CONFIGURE GPIO PINS */
    // Clear mode bits for PA10 (Input) and PA5
    GPIOA_MODER &= ~((3 << 20) | (3 << 10));
    // Set PA5 as General Purpose Output (01)
    GPIOA_MODER |= (1 << 10);

    // Clear mode bits for PB12 to set it as Input (00)
    GPIOB_MODER &= ~(3 << 24);
    // Prevent the pin from floating (Attach the "Spring")
    GPIOA_PUPDR &= ~(3 << 20); // First, clear bits 20 and 21
    GPIOB_PUPDR &= ~(3 << 24); // First, clear bits 24 and 25

    GPIOA_PUPDR |= (1 << 20); // Write '01': Enable the internal Pull-Up resistor
    GPIOB_PUPDR |= (1 << 24); // Write '01': Enable the internal Pull-Up resistor

    /* C. CONFIGURE SYSCFG ROUTING */
    // Route EXTI10 to Port A (Clear bits 8-11 to set value 0000)
    SYSCFG_EXTICR3 &= ~(0xF << 8);

    // Route EXTI12 to Port B (Clear bits 0-3, then set value 0001)
    SYSCFG_EXTICR4 &= ~(0xF << 0);
    SYSCFG_EXTICR4 |= (1 << 0);

    /* D. CONFIGURE EXTI LOGIC */
    // Unmask (Enable) EXTI lines 10 and 12
    EXTI_IMR |= ((1 << 10) | (1 << 12));

    // Set trigger to Falling Edge for both lines 10 and 12
    EXTI_FTSR |= ((1 << 10) | (1 << 12));

    /* E. ENABLE NVIC */
    // EXTI15_10 corresponds to IRQ 40.
    // IRQ 40 is in ISER1 (40 / 32 = 1) at bit 8 (40 % 32 = 8).
    NVIC_ISER1 |= (1 << 8);

    /* F. MAIN LOOP */
    while(1){
        // The CPU idles here. Operations are entirely event-driven.
    }
}
