/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/**
 * Bare-metal Interrupt Example for STM32F401RE
 * Objective: Toggle LED (PA5) using an external interrupt on PB4 (Rising Edge)
 */

#include <stdint.h>

/* --- Register Mapping (Memory Addresses) --- */
// Clock Control Registers
#define RCC_AHB1ENR (*(volatile uint32_t *)0x40023830) // GPIO Clock Enable
#define RCC_APB2ENR (*(volatile uint32_t *)0x40023844) // System Configuration Clock Enable

// GPIO Registers
#define GPIOA_MODER (*(volatile uint32_t *)0x40023844) // Mode register for Port A
#define GPIOA_ODR   (*(volatile uint32_t *)0x40020014) // Output data register for Port A
#define GPIOB_MODER (*(volatile uint32_t *)0x40020400) // Mode register for Port B

// System Configuration Register (Mux for EXTI)
#define SYSCFG_EXTICR2 (*(volatile uint32_t *)0x4001380C) // External Interrupt Config Reg 2 (Pins 4-7)

// EXTI (External Interrupt Controller) Registers
#define EXTI_IMR  (*(volatile uint32_t *)0x40013C00) // Interrupt Mask Register
#define EXTI_RTSR (*(volatile uint32_t *)0x40013C08) // Rising Trigger Selection Register
#define EXTI_PR   (*(volatile uint32_t *)0x40013C14) // Pending Register (Status flags)

// NVIC (Nested Vectored Interrupt Controller) - Core ARM Peripheral
#define NVIC_ISER0 *((volatile uint32_t *)0xE000E100) // Interrupt Set-Enable Register 0

/**
 * Interrupt Service Routine (ISR) for EXTI Line 4
 * Note: The name must exactly match the Vector Table defined in the startup file.
 */
void EXTI4_IRQHandler(void){
    // Clear the pending bit for line 4 by writing '1' to it (rc_w1)
    // If not cleared, the CPU will re-enter the interrupt infinitely.
    EXTI_PR |= (1 << 4);

    // Toggle PA5 (LD2 on Nucleo-F401RE) using XOR operator
    GPIOA_ODR ^= (1 << 5);
}

int main(void)
{
    /* 1. ENABLE PERIPHERAL CLOCKS */
    // Enable GPIOA (bit 0) and GPIOB (bit 1) clocks
    RCC_AHB1ENR |= (3 << 0);
    // Enable SYSCFG clock (bit 14) required to route GPIO to EXTI
    RCC_APB2ENR |= (1 << 14);

    /* 2. CONFIGURE GPIO MODES */
    // Set PA5 as General Purpose Output (01 in bits 10-11)
    GPIOA_MODER &= ~(3 << 10); // Clear bits 10 and 11
    GPIOA_MODER |= (1 << 10);  // Set bit 10

    // Set PB4 as Input (00 in bits 8-9)
    GPIOB_MODER &= ~(3 << 8);

    /* 3. CONFIGURE SYSCFG (SIGNAL ROUTING) */
    // Map EXTI4 line to Port B.
    // SYSCFG_EXTICR2 bits [3:0] control EXTI4. Value 0001 selects Port B.
    SYSCFG_EXTICR2 &= ~(0xF << 0); // Clear the 4-bit field for EXTI4
    SYSCFG_EXTICR2 |= (1 << 0);    // Set value to 1 (Port B)

    /* 4. CONFIGURE EXTI (DETECTION LOGIC) */
    // Unmask EXTI line 4 (Enable the interrupt line)
    EXTI_IMR |= (1 << 4);
    // Enable Rising Edge trigger for line 4 (Detect 0V to 3.3V transition)
    EXTI_RTSR |= (1 << 4);

    /* 5. CONFIGURE NVIC (CPU CORE ENABLE) */
    // Enable Interrupt Request (IRQ) number 10, which corresponds to EXTI4
    NVIC_ISER0 |= (1 << 10);

    /* 6. MAIN LOOP */
    while(1){
        // Do nothing. The CPU stays here until the interrupt occurs.
        // The hardware handles the jump to EXTI4_IRQHandler.
    }
}
