/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

/* ========================================================================== */
/* 1. REGISTER MEMORY MAPPING                                                 */
/* ========================================================================== */

// Clock Control Registers
#define RCC_AHB1ENR     (*(volatile uint32_t *)0x40023830) // GPIO Clocks
#define RCC_APB1ENR     (*(volatile uint32_t *)0x40023840) // TIM2 Clock
#define RCC_APB2ENR     (*(volatile uint32_t *)0x40023844) // SYSCFG Clock

// GPIO Registers
#define GPIOA_MODER     (*(volatile uint32_t *)0x40020000)
#define GPIOB_MODER     (*(volatile uint32_t *)0x40020400)
#define GPIOA_PUPDR     (*(volatile uint32_t *)0x4002000C)
#define GPIOB_PUPDR     (*(volatile uint32_t *)0x4002040C)
#define GPIOA_AFRL      (*(volatile uint32_t *)0x40020020) // Alternate Function Low

// System Configuration (EXTI Routing)
#define SYSCFG_EXTICR3  (*(volatile uint32_t *)0x40013810) // EXTI 8 to 11
#define SYSCFG_EXTICR4  (*(volatile uint32_t *)0x40013814) // EXTI 12 to 15

// EXTI Registers
#define EXTI_IMR        (*(volatile uint32_t *)0x40013C00) // Interrupt Mask
#define EXTI_FTSR       (*(volatile uint32_t *)0x40013C0C) // Falling Trigger Selection
#define EXTI_PR         (*(volatile uint32_t *)0x40013C14) // Pending Register

// NVIC Register
#define NVIC_ISER1      (*(volatile uint32_t *)0xE000E104) // IRQ 32-63 (EXTI15_10 is IRQ 40)

// SysTick Registers
#define SYSTICK_CTRL    (*(volatile uint32_t *)0xE000E010) // Control and Status
#define SYSTICK_LOAD    (*(volatile uint32_t *)0xE000E014) // Reload Value

// TIM2 Registers (Base Address: 0x40000000)
#define TIM2_BASE       0x40000000
#define TIM2_CR1        (*(volatile uint32_t *)(TIM2_BASE + 0x00)) // Control Register 1
#define TIM2_CCMR1      (*(volatile uint32_t *)(TIM2_BASE + 0x18)) // Capture/Compare Mode 1
#define TIM2_CCER       (*(volatile uint32_t *)(TIM2_BASE + 0x20)) // Capture/Compare Enable
#define TIM2_PSC        (*(volatile uint32_t *)(TIM2_BASE + 0x28)) // Prescaler
#define TIM2_ARR        (*(volatile uint32_t *)(TIM2_BASE + 0x2C)) // Auto-Reload
#define TIM2_CCR1       (*(volatile uint32_t *)(TIM2_BASE + 0x34)) // Capture/Compare 1 (Duty Cycle)


/* ========================================================================== */
/* 2. GLOBAL VARIABLES                                                        */
/* ========================================================================== */

#define DEBOUNCE_TIME 50 // 50ms window to ignore mechanical bounces

volatile uint32_t ms_counter = 0;       // Global system time (updated by SysTick)
volatile uint32_t fade_delay = 10;      // Wait time between brightness steps (ms)

volatile uint32_t last_pa10_press = 0;  // Timestamp for Debouncing Button 1
volatile uint32_t last_pb12_press = 0;  // Timestamp for Debouncing Button 2


/* ========================================================================== */
/* 3. INTERRUPT SERVICE ROUTINES (ISR)                                        */
/* ========================================================================== */

/**
 * @brief SysTick Handler - Triggers every 1 ms
 */
void SysTick_Handler(void) {
    ms_counter++;
}

/**
 * @brief EXTI Lines 10 to 15 Handler (Triggered by PA10 or PB12)
 */
void EXTI15_10_IRQHandler(void) {

    // Freeze current time for accurate debouncing calculations
    uint32_t current_time = ms_counter;

    /* --- CHECK PA10 (FASTER FADE) --- */
    if (EXTI_PR & (1 << 10)) {
        EXTI_PR |= (1 << 10); // 1. Clear the flag immediately

        // 2. Debouncing check
        if ((current_time - last_pa10_press) > DEBOUNCE_TIME) {

            // 3. Decrease delay to make the animation faster (min limit: 2ms)
            if (fade_delay > 2) {
                fade_delay -= 2;
            }
            last_pa10_press = current_time; // 4. Update timestamp
        }
    }

    /* --- CHECK PB12 (SLOWER FADE) --- */
    if (EXTI_PR & (1 << 12)) {
        EXTI_PR |= (1 << 12); // 1. Clear the flag immediately

        // 2. Debouncing check
        if ((current_time - last_pb12_press) > DEBOUNCE_TIME) {

            // 3. Increase delay to make the animation slower (max limit: 30ms)
            if (fade_delay < 30) {
                fade_delay += 2;
            }
            last_pb12_press = current_time; // 4. Update timestamp
        }
    }
}


/* ========================================================================== */
/* 4. MAIN PROGRAM                                                            */
/* ========================================================================== */

int main(void) {

    /* --- A. CLOCKS --- */
    RCC_AHB1ENR |= (3 << 0);  // Enable GPIOA and GPIOB
    RCC_APB1ENR |= (1 << 0);  // Enable TIM2
    RCC_APB2ENR |= (1 << 14); // Enable SYSCFG

    /* --- B. GPIO CONFIGURATION --- */
    // Clear mode bits for PA5, PA10, and PB12
    GPIOA_MODER &= ~((3 << 10) | (3 << 20));
    GPIOB_MODER &= ~(3 << 24);

    // Set PA5 to Alternate Function Mode (10)
    GPIOA_MODER |= (2 << 10);

    // Route PA5 to TIM2_CH1 using AFRL (Alternate Function 1)
    GPIOA_AFRL &= ~(0xF << 20); // Clear bits 20-23
    GPIOA_AFRL |=  (1 << 20);   // Write '0001'

    // Enable Pull-Up resistors for the inputs (PA10, PB12)
    GPIOA_PUPDR &= ~(3 << 20);
    GPIOB_PUPDR &= ~(3 << 24);
    GPIOA_PUPDR |= (1 << 20);
    GPIOB_PUPDR |= (1 << 24);

    /* --- C. EXTI & SYSCFG CONFIGURATION --- */
    // Route Lines to Ports
    SYSCFG_EXTICR3 &= ~(0xF << 8); // Route Line 10 to Port A
    SYSCFG_EXTICR4 &= ~(0xF << 0); // Clear Line 12
    SYSCFG_EXTICR4 |=  (1 << 0);   // Route Line 12 to Port B

    // Unmask and set falling edge trigger
    EXTI_IMR  |= ((1 << 10) | (1 << 12));
    EXTI_FTSR |= ((1 << 10) | (1 << 12));

    // Enable EXTI IRQ in NVIC
    NVIC_ISER1 |= (1 << 8); // IRQ 40 (EXTI15_10)

    /* --- D. SYSTICK CONFIGURATION --- */
    SYSTICK_CTRL = 0;
    SYSTICK_LOAD = 16000 - 1; // 1 ms tick @ 16MHz
    SYSTICK_CTRL |= ((1 << 2) | (1 << 1) | (1 << 0)); // Start SysTick

    /* --- E. TIM2 PWM CONFIGURATION --- */
    // 1. Slow down clock to 1 MHz (1 tick = 1 us)
    TIM2_PSC = 16 - 1;

    // 2. Set period to 1000 us -> 1 kHz PWM Frequency
    TIM2_ARR = 1000 - 1;

    // 3. Set Channel 1 to PWM Mode 1 (Write '110' to OC1M bits)
    TIM2_CCMR1 &= ~(7 << 4);
    TIM2_CCMR1 |=  (6 << 4);

    // 4. Enable Channel 1 Output
    TIM2_CCER |= (1 << 0);

    // 5. Start with LED off (0% Duty Cycle)
    TIM2_CCR1 = 0;

    // 6. Start the Timer
    TIM2_CR1 |= (1 << 0);

    /* --- F. MAIN LOOP (FADING LOGIC) --- */
    int brightness = 0;
    int fade_step = 5;
    uint32_t last_fade_update = 0;

    while(1) {

        // Non-blocking delay check:
        // Only update the brightness if 'fade_delay' milliseconds have passed
        if ((ms_counter - last_fade_update) >= fade_delay) {

            last_fade_update = ms_counter; // Reset the software timer

            // 1. Write the new duty cycle to the hardware
            TIM2_CCR1 = brightness;

            // 2. Calculate the next brightness level
            brightness += fade_step;

            // 3. Reverse direction when limits are hit (0% or 100%)
            if (brightness <= 0 || brightness >= 1000) {
                fade_step = -fade_step;
            }
        }

        // The CPU is free here! It loops extremely fast doing nothing,
        // until the SysTick increments ms_counter enough to trigger the next frame.
    }
}
